import { useEffect, useMemo, useState } from 'react';
import { formatTimestamp } from '../../timestamps.ts';
import { requestJson } from '../../forms-client.ts';
import { CommandOverlayTrigger } from './CommandOverlayStack.tsx';
import type { CommandEntity } from './types.ts';

export function CommandFilterToolbar({ query, onQuery, statuses, status, onStatus, kinds, kind, onKind, tags, tag, onTag }: { query: string; onQuery: (value: string) => void; statuses?: string[]; status?: string; onStatus?: (value: string) => void; kinds?: string[]; kind?: string; onKind?: (value: string) => void; tags?: string[]; tag?: string; onTag?: (value: string) => void }) {
	return <form className="ts-command-filters" role="search" onSubmit={(event) => event.preventDefault()}><label><span>Search records</span><input type="search" value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Search names, evidence, status…" /></label>{statuses?.length ? <label><span>Status</span><select value={status} onChange={(event) => onStatus?.(event.target.value)}><option value="">All statuses</option>{statuses.map((value) => <option key={value}>{value}</option>)}</select></label> : null}{kinds?.length ? <label><span>Type</span><select value={kind} onChange={(event) => onKind?.(event.target.value)}><option value="">All types</option>{kinds.map((value) => <option key={value}>{value}</option>)}</select></label> : null}{tags?.length ? <label><span>Classification</span><select value={tag} onChange={(event) => onTag?.(event.target.value)}><option value="">All classifications</option>{tags.map((value) => <option key={value}>{value}</option>)}</select></label> : null}</form>;
}

export function CommandEntityCard({ item, stateEndpoint, timeZone }: { item: CommandEntity; stateEndpoint?: string; timeZone: string }) {
	const [state, setState] = useState({ pinned: item.pinned === true, hidden: item.hidden === true, resolved: item.resolved === true });
	async function change(field: 'pinned' | 'hidden' | 'resolved') { const next = !state[field]; setState((current) => ({ ...current, [field]: next })); if (!stateEndpoint) return; const response = await requestJson(stateEndpoint, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ kind: item.kind, id: item.id, [field]: next }) }); if (!response.ok) setState((current) => ({ ...current, [field]: !next })); }
	return <article className="ts-command-card" data-kind={item.kind} data-severity={item.severity ?? ''} data-pinned={state.pinned}><header><span className="ts-command-card__kind">{item.kind.replace(/-/gu, ' ')}</span><div className="ts-command-card__actions">{stateEndpoint ? <><button type="button" aria-pressed={state.pinned} onClick={() => void change('pinned')}>{state.pinned ? 'Pinned' : 'Pin'}</button><button type="button" onClick={() => void change('hidden')}>Hide</button>{item.kind === 'error' && item.actionable ? <button type="button" aria-pressed={state.resolved} onClick={() => void change('resolved')}>{state.resolved ? 'Resolved' : 'Resolve'}</button> : null}</> : null}{item.status ? <span className="ts-command-card__status">{item.status}</span> : null}</div></header><h3>{item.title}</h3><p>{item.description}</p>{item.metrics?.length ? <dl>{item.metrics.slice(0, 6).map((metric) => <div key={metric.label}><dt>{metric.label}</dt><dd>{metric.value}</dd></div>)}</dl> : null}<footer><div>{item.projectName ? <span>{item.projectName}</span> : null}{item.activityProfile ? <span>{item.activityProfile}</span> : null}{item.occurredAt ? <time dateTime={item.occurredAt}>{formatTimestamp(item.occurredAt, { timeZone })}</time> : null}{item.tags?.slice(0, 2).map((tag) => <span key={tag}>{tag}</span>)}</div><CommandOverlayTrigger target={{ kind: item.kind, id: item.id }}>Inspect <span aria-hidden="true">→</span></CommandOverlayTrigger></footer></article>;
}

export function CommandCollection({ items, empty = 'No matching command records.', initialQuery = '', splitLabel, stateEndpoint, timeZone }: { items: CommandEntity[]; empty?: string; initialQuery?: string; splitLabel?: string; stateEndpoint?: string; timeZone: string }) {
	const [query, setQuery] = useState(initialQuery); const [status, setStatus] = useState(''); const [kind, setKind] = useState(''); const [tag,setTag] = useState(''); const [showHidden, setShowHidden] = useState(false); const [urlReady, setUrlReady] = useState(false);
	const filterKey = useMemo(() => (splitLabel ?? 'records').toLowerCase().replace(/[^a-z0-9]+/gu, '-').replace(/^-|-$/gu, ''), [splitLabel]);
	useEffect(() => { const url = new URL(window.location.href); setQuery(url.searchParams.get(`filter.${filterKey}.q`) ?? initialQuery); setStatus(url.searchParams.get(`filter.${filterKey}.status`) ?? ''); setKind(url.searchParams.get(`filter.${filterKey}.kind`) ?? ''); setTag(url.searchParams.get(`filter.${filterKey}.tag`) ?? ''); setShowHidden(url.searchParams.get(`filter.${filterKey}.hidden`) === 'true'); setUrlReady(true); }, [filterKey, initialQuery]);
	useEffect(() => { if (!urlReady) return; const url = new URL(window.location.href); const values = { q: query, status, kind, tag, hidden: showHidden ? 'true' : '' }; for (const [name, value] of Object.entries(values)) { const key = `filter.${filterKey}.${name}`; if (value) url.searchParams.set(key, value); else url.searchParams.delete(key); } history.replaceState(history.state, '', url); }, [filterKey, kind, query, showHidden, status, tag, urlReady]);
	const statuses = useMemo(() => [...new Set(items.map((item) => item.status).filter((value): value is string => Boolean(value)))].sort(), [items]);
	const kinds = useMemo(() => [...new Set(items.map((item) => item.kind))].sort(), [items]);
	const tags = useMemo(() => [...new Set(items.flatMap((item) => item.tags ?? []))].sort(),[items]);
	const visible = useMemo(() => items.filter((item) => (showHidden || !item.hidden) && (!query || `${item.title} ${item.description} ${item.projectName ?? ''}`.toLowerCase().includes(query.toLowerCase())) && (!status || item.status === status) && (!kind || item.kind === kind) && (!tag || item.tags?.includes(tag))), [items, kind, query, showHidden, status, tag]);
	return <section className="ts-command-collection" aria-label={splitLabel}><CommandFilterToolbar query={query} onQuery={setQuery} statuses={statuses} status={status} onStatus={setStatus} kinds={kinds} kind={kind} onKind={setKind} tags={tags} tag={tag} onTag={setTag} /><div className="ts-command-collection__summary"><strong>{visible.length}</strong><span>{splitLabel ?? 'records'} visible</span>{items.some((item) => item.hidden) ? <label><input type="checkbox" checked={showHidden} onChange={(event) => setShowHidden(event.target.checked)} /> Show hidden</label> : null}</div>{visible.length ? <div className="ts-command-card-grid">{visible.map((item) => <CommandEntityCard key={`${item.kind}:${item.id}`} item={item} stateEndpoint={stateEndpoint} timeZone={timeZone} />)}</div> : <div className="ts-command-empty">{empty}</div>}</section>;
}
