import { useEffect, useRef, useState } from 'react';
import { CommandCollection } from './CommandCollection.tsx';
import { YamlIde, type YamlIdeDiagnostic } from './YamlIde.tsx';
import type { CommandEntity, CommandWorkspaceEndpoints } from './types.ts';

interface Draft { projectId: string; projectName: string; seedPath: string; scenePath: string; seedYaml: string; sceneYaml: string; expectedBase: string; diagnostics: YamlIdeDiagnostic[] }
function requestId() { return globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`; }

export function SimulationBay({ items, endpoints, stateEndpoint, timeZone }: { items: CommandEntity[]; endpoints: CommandWorkspaceEndpoints; stateEndpoint: string; timeZone: string }) {
	const [draft,setDraft] = useState<Draft | null>(null); const [seed,setSeed] = useState(''); const [scene,setScene] = useState(''); const [commit,setCommit] = useState(''); const [message,setMessage] = useState('Loading the current team profile…'); const [busy,setBusy] = useState(''); const loaded = useRef(false);
	useEffect(() => { if (loaded.current || !endpoints.draft) return; loaded.current = true; const controller = new AbortController(); void fetch(endpoints.draft, { signal: controller.signal }).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error ?? 'Could not generate the team simulation draft.'); const next = result.payload as Draft; setDraft(next); setSeed(next.seedYaml); setScene(next.sceneYaml); setMessage(next.diagnostics?.length ? 'The generated profile needs attention before launch.' : 'Generated from the current team, repositories, memberships, and local provider.'); }).catch((error) => { if (error?.name !== 'AbortError') setMessage(error instanceof Error ? error.message : 'Draft unavailable.'); }); return () => controller.abort(); }, [endpoints.draft]);
	async function save() { if (!draft || !endpoints.authoringBundle) return; setBusy('save'); setMessage('Validating and committing both definitions through TreeDX…'); try { const response = await fetch(endpoints.authoringBundle, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ projectId: draft.projectId, expectedBase: draft.expectedBase, changeSummary: 'Agent Lab simulation definition', files: [{ path: draft.seedPath, source: seed }, { path: draft.scenePath, source: scene }] }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? 'The definitions could not be committed.'); setCommit(String(result.payload.commit)); setMessage(`Saved both definitions at ${String(result.payload.commit).slice(0,12)}.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Save failed.'); } finally { setBusy(''); } }
	async function launch(rerun = false) { if (!draft || !commit || !endpoints.simulations) return; setBusy('launch'); setMessage('Queueing the committed scene for the seeded provider manager…'); try { const response = await fetch(endpoints.simulations, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ projectId: draft.projectId, scenePath: draft.scenePath, immutableRef: commit, requestId: requestId(), rerun }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? 'Simulation launch failed.'); setMessage(`Simulation ${String(result.payload.id).slice(0,12)} queued. Follow it below without leaving this workspace.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Launch failed.'); } finally { setBusy(''); } }
	const simulations = items.filter((item) => item.kind === 'simulation');
	return <section className="ts-command-bay"><header><div><span>Production path</span><h2>Simulation Bay</h2><p>Generate a secret-free team profile, author both YAML definitions atomically, then launch the immutable scene through the existing provider.</p></div><div className="ts-simulation-bay__actions"><button type="button" onClick={save} disabled={!draft || Boolean(busy)}>Save definitions</button><button type="button" onClick={() => void launch()} disabled={!commit || Boolean(busy)}>Launch simulation</button></div></header>{draft ? <><div className="ts-simulation-bay__identity"><strong>{draft.projectName}</strong><span>{commit ? `Immutable ref ${commit.slice(0,12)}` : 'Working draft'}</span></div><div className="ts-simulation-bay__editors"><section><header><span>Seed profile</span><code>{draft.seedPath}</code></header><YamlIde value={seed} onChange={(value) => { setSeed(value); setCommit(''); }} label="Seed YAML" diagnostics={draft.diagnostics} /></section><section><header><span>Scene definition</span><code>{draft.scenePath}</code></header><YamlIde value={scene} onChange={(value) => { setScene(value); setCommit(''); }} label="Scene YAML" /></section></div></> : <div className="ts-command-empty">Generating the current team profile…</div>}<p role="status">{message}</p>{simulations.length ? <section><header><div><span>Retained runs</span><h3>Follow, inspect, cancel, or rerun</h3></div></header><CommandCollection items={simulations} splitLabel="simulations" stateEndpoint={stateEndpoint} timeZone={timeZone} /></section> : null}</section>;
}
