import { useState } from 'react';
import { requestJson } from '../../../forms-client.ts';
import { stringify } from 'yaml';

function slug(value: string) { return value.trim().toLowerCase().replace(/[^a-z0-9]+/gu,'-').replace(/^-|-$/gu,''); }
export function AgentCreator({ projects,saveEndpoint,onClose }: { projects: Array<[string,string]>; saveEndpoint: string; onClose: () => void }) {
	const [projectId,setProjectId] = useState(projects[0]?.[0] ?? ''); const [name,setName] = useState(''); const [identity,setIdentity] = useState(''); const [agentClass,setAgentClass] = useState('planning'); const [state,setState] = useState('');
	async function create() {
		const agentSlug = slug(identity || name); if (!projectId || !agentSlug || !name.trim()) { setState('Choose a project and provide a name and identity.'); return; }
		const definition = { id:`agent:${agentSlug}`,slug:agentSlug,title:name,name,agentClass,projectAgentClassId:agentClass,enabled:true,description:`Investigates assigned objectives and publishes evidence for coordinated planning.`,identity:{purpose:`Contribute ${name} expertise to the project signal graph.`,responsibilities:['Inspect authoritative context','Publish evidence with provenance','Escalate uncertainty'],durableInstructions:'Use TreeDX for content access. Never vote, decide, or act without governed authority.'},activityProfiles:{planning:{activityType:'planning',enabled:true,handler:'writer',prompt:{system:`You are ${name}. Research the assigned objective through TreeDX, distinguish evidence from inference, and produce a concise evidence note for downstream planning.`,task:'Investigate the assigned objective and publish evidence with immutable provenance.'},planningIntent:{stage:'discovery',objective:'Discover useful evidence for coordinated planning',artifactKind:'evidence_note',subjectModel:'objective',subjectId:null},branchPolicy:{kind:'staging-content',base:'staging'},contentAccess:{read:{models:['objective','note','proposal','knowledge'],actions:['describe','query','read']},write:{models:['note','question'],actions:['create','link','validate','commit']},commit:{allowed:true}},tools:{allowed:['treeseed.content.describe','treeseed.content.query','treeseed.content.read','treeseed.content.create','treeseed.content.commit']},signals:{subscribesTo:[{contract:'workday-started'}],publishes:['evidence-ready']},outputs:{messageTypes:['research_evidence_ready'],modelMutations:['linked_note:create']},questionPolicy:{blockExecutionWhenCreated:true,defaultAnswerPolicy:{kind:'team-human'}},execution:{providerPreference:['codex'],maxRuntimeSeconds:300,maxRetries:1,verificationRequired:false}}}};
		const source=`---\n${stringify(definition).trim()}\n---\n\n${name} participates through declared signals; durable outputs remain evidence.\n`; setState('Validating and committing the agent template…'); const response=await requestJson(saveEndpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId,path:`src/content/agents/${agentSlug}.mdx`,source,changeSummary:`Create agent ${name}`})}); const result=await response.json(); if(!response.ok){setState(result.error ?? 'Agent creation failed.');return;} setState(`Created at ${String(result.payload?.commit ?? '').slice(0,12)}.`); setTimeout(onClose,500);
	}
	return <section className="ts-agent-creator" role="dialog" aria-modal="true" aria-label="Create repository agent"><header><div><span>Validated repository template</span><h3>Create an agent</h3><p>The new agent joins the canvas only after TreeDX commit and live class reconciliation.</p></div><button type="button" onClick={onClose} aria-label="Close creator">×</button></header><div><label><span>Project</span><select value={projectId} onChange={(event)=>setProjectId(event.target.value)}>{projects.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label><span>Name</span><input value={name} onChange={(event)=>{setName(event.target.value);if(!identity)setIdentity(slug(event.target.value));}} /></label><label><span>Identity</span><input value={identity} onChange={(event)=>setIdentity(slug(event.target.value))} /></label><label><span>Agent class</span><input value={agentClass} onChange={(event)=>setAgentClass(slug(event.target.value))} /></label></div><footer><button type="button" onClick={onClose}>Cancel</button><button type="button" onClick={()=>void create()}>Create & reconcile</button>{state?<span role="status">{state}</span>:null}</footer></section>;
}
