import { useEffect,useMemo, useRef, useState, type CSSProperties, type PointerEvent as ReactPointerEvent } from 'react';
import { requestJson } from '../../../forms-client.ts';
import type { CommandEntity, CommandRelation } from '../types.ts';
import { CommandOverlayTrigger } from '../overlay-navigation.tsx';
import { AgentCreator } from './AgentCreator.tsx';
import { GroupCreator } from './GroupCreator.tsx';

type Point = { x: number; y: number };
const NODE_WIDTH = 176;
const NODE_HEIGHT = 72;
function record(value: unknown): Record<string, unknown> { return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function savedPoint(item: CommandEntity): Point | null { const value = record(record(item.data).layout); const x = Number(value.x); const y = Number(value.y); return Number.isFinite(x) && Number.isFinite(y) ? { x, y } : null; }
export function creatorUrl(href: string, creating: 'agent'|'group'|null) { const url=new URL(href); if(creating)url.searchParams.set('create',creating);else url.searchParams.delete('create');return `${url.pathname}${url.search}${url.hash}`; }

function layered(items: CommandEntity[], relations: CommandRelation[]) {
	const ids = new Set(items.map((item) => item.id)); const incoming = new Map(items.map((item) => [item.id, 0])); const outgoing = new Map(items.map((item) => [item.id, [] as string[]]));
	for (const relation of relations) if (ids.has(relation.from) && ids.has(relation.to)) { incoming.set(relation.to, (incoming.get(relation.to) ?? 0) + 1); outgoing.get(relation.from)?.push(relation.to); }
	const rank = new Map<string, number>(); const ready = items.filter((item) => incoming.get(item.id) === 0).map((item) => item.id).sort();
	while (ready.length) { const id = ready.shift()!; const current = rank.get(id) ?? 0; for (const target of outgoing.get(id) ?? []) { rank.set(target, Math.max(rank.get(target) ?? 0, current + 1)); const count = (incoming.get(target) ?? 1) - 1; incoming.set(target, count); if (!count) ready.push(target); } ready.sort(); }
	const cyclic = items.filter((item) => (incoming.get(item.id) ?? 0) > 0).map((item) => item.id); cyclic.forEach((id, index) => rank.set(id, Math.max(1, ...rank.values()) + 1 + index % 2));
	const groups = new Map<number, CommandEntity[]>(); for (const item of items) { const level = rank.get(item.id) ?? 0; groups.set(level, [...(groups.get(level) ?? []), item]); }
	const points = new Map<string, Point>(); for (const [level, group] of [...groups].sort(([a], [b]) => a - b)) group.sort((a, b) => a.title.localeCompare(b.title)).forEach((item, index) => points.set(item.id, { x: 44 + level * 270, y: 50 + index * 112 }));
	return { points, cyclic };
}

export function AgentFlowCanvas({ items, relations, projects: projectOptions = [], stateEndpoint, authoringEndpoint }: { items: CommandEntity[]; relations: CommandRelation[]; projects?: Array<{id:string;name:string}>; stateEndpoint?: string; authoringEndpoint?: string }) {
	const [query, setQuery] = useState(''); const [project, setProject] = useState(''); const [showGroups,setShowGroups]=useState(false); const [creating,setCreating] = useState<'agent'|'group'|null>(null); const [positions, setPositions] = useState<Record<string, Point>>({}); const [zoom, setZoom] = useState(1); const [layoutRevision, setLayoutRevision] = useState(0); const drag = useRef<{ id: string; start: Point; origin: Point } | null>(null); const viewport=useRef<HTMLDivElement>(null); const projectReady=useRef(false);
	useEffect(()=>{const sync=()=>{const requested=new URL(location.href).searchParams.get('create');setCreating(requested==='agent'||requested==='group'?requested:null)};sync();addEventListener('popstate',sync);return()=>removeEventListener('popstate',sync)},[]);
	const connected = useMemo(() => new Set(relations.flatMap((relation) => [relation.from, relation.to])), [relations]);
	const projects = useMemo(() => [...new Map([...projectOptions.map((item)=>[item.id,item.name] as const),...items.filter((item) => item.projectId).map((item) => [item.projectId!, item.projectName ?? 'Project'] as const)]).entries()], [items,projectOptions]);
	useEffect(()=>{if(projectReady.current||!projects.length)return;const requested=new URL(location.href).searchParams.get('project');setProject(projects.some(([id])=>id===requested)?requested!:projects[0]![0]);projectReady.current=true;},[projects]);
	const visible = useMemo(() => {
		const matchesText = (item: CommandEntity) => !query || `${item.title} ${item.description} ${item.tags?.join(' ')}`.toLowerCase().includes(query.toLowerCase());
		const agents = items.filter((item) => item.kind === 'agent' && (!project || item.projectId === project) && matchesText(item));
		const agentIds = new Set(agents.map((item) => item.id));
		const relatedSignals = new Set(relations.filter((relation) => agentIds.has(relation.from) || agentIds.has(relation.to)).flatMap((relation) => [relation.from,relation.to]));
		return items.filter((item) => item.kind === 'agent' ? agentIds.has(item.id) : item.kind === 'signal' ? relatedSignals.has(item.id) && (!query || matchesText(item) || connected.has(item.id)) : showGroups && ['group','group-edge'].includes(item.kind) && (!project || item.projectId === project) && matchesText(item));
	}, [connected,items,project,query,relations,showGroups]);
	const visibleIds = useMemo(() => new Set(visible.map((item) => item.id)), [visible]); const links = useMemo(() => relations.filter((relation) => visibleIds.has(relation.from) && visibleIds.has(relation.to)), [relations, visibleIds]); const generated = useMemo(() => layered(visible, links), [visible, links, layoutRevision]);
	const point = (item: CommandEntity) => positions[item.id] ?? savedPoint(item) ?? generated.points.get(item.id) ?? { x: 30, y: 30 };
	const bounds = useMemo(() => { const values = visible.map(point); return { width: Math.max(720, ...values.map((value) => value.x + NODE_WIDTH + 60)), height: Math.max(360, ...values.map((value) => value.y + NODE_HEIGHT + 60)) }; }, [visible, positions, generated.points]);
	function redraw() { setPositions({}); setZoom(1); setLayoutRevision((value) => value + 1); }
	function setCreator(value:'agent'|'group'|null){setCreating(value);history.pushState(null,'',creatorUrl(location.href,value));}
	function fit() { const frame=viewport.current;if(!frame)return;setZoom(Math.max(.45,Math.min(1.35,(frame.clientWidth-24)/bounds.width,(frame.clientHeight-24)/bounds.height)));frame.scrollTo({left:0,top:0}); }
	function startDrag(event: ReactPointerEvent, item: CommandEntity) { if ((event.target as HTMLElement).closest('button')) return; const origin = point(item); drag.current = { id: item.id, start: { x: event.clientX, y: event.clientY }, origin }; event.currentTarget.setPointerCapture(event.pointerId); }
	function moveDrag(event: ReactPointerEvent) { const active = drag.current; if (!active) return; setPositions((current) => ({ ...current, [active.id]: { x: Math.max(12, active.origin.x + (event.clientX - active.start.x) / zoom), y: Math.max(12, active.origin.y + (event.clientY - active.start.y) / zoom) } })); }
	async function endDrag(event: ReactPointerEvent, item: CommandEntity) { if (!drag.current) return; event.currentTarget.releasePointerCapture(event.pointerId); drag.current = null; const value = positions[item.id] ?? point(item); if (stateEndpoint) await requestJson(stateEndpoint, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ namespace: 'command', kind: item.kind, id: item.id, layout: value }) }).catch(() => null); }
	return <section className="ts-agent-flow" aria-label="Agent signal dependency graph">
		<header className="ts-agent-flow__toolbar"><label><span>Find agent or signal</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} /></label><label><span>Project</span><select value={project} onChange={(event) => setProject(event.target.value)}><option value="">All projects</option>{projects.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><div>{authoringEndpoint?<><button type="button" onClick={()=>setCreator('agent')}>Create agent</button><button type="button" onClick={()=>setCreator('group')}>Create group</button></>:null}<button type="button" aria-pressed={showGroups} onClick={()=>setShowGroups((value)=>!value)}>{showGroups?'Hide groups':'Show groups'}</button><button type="button" onClick={redraw}>Redraw flow</button><button type="button" onClick={fit}>Fit</button><button type="button" onClick={() => setZoom((value) => Math.max(.45, value - .1))} aria-label="Zoom out">−</button><output>{Math.round(zoom * 100)}%</output><button type="button" onClick={() => setZoom((value) => Math.min(1.8, value + .1))} aria-label="Zoom in">+</button></div></header>
		{generated.cyclic.length ? <p className="ts-agent-flow__diagnostic" role="alert">Cycle detected across {generated.cyclic.length} nodes. Correct the connected agents’ signal declarations.</p> : null}
		<div ref={viewport} className="ts-agent-flow__viewport" tabIndex={0} onKeyDown={(event)=>{const frame=viewport.current;if(!frame||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;event.preventDefault();frame.scrollBy({left:event.key==='ArrowLeft'?-60:event.key==='ArrowRight'?60:0,top:event.key==='ArrowUp'?-60:event.key==='ArrowDown'?60:0});}} onWheel={(event) => { if (!event.ctrlKey) return; event.preventDefault(); setZoom((value) => Math.max(.45, Math.min(1.8, value - event.deltaY * .001))); }}><div className="ts-agent-flow__canvas" style={{ width: bounds.width, height: bounds.height, transform: `scale(${zoom})` } as CSSProperties}>
			<svg aria-hidden="true" viewBox={`0 0 ${bounds.width} ${bounds.height}`}>{links.map((relation) => { const fromItem = visible.find((item) => item.id === relation.from); const toItem = visible.find((item) => item.id === relation.to); if (!fromItem || !toItem) return null; const from = point(fromItem); const to = point(toItem); const middle = (from.x + NODE_WIDTH + to.x) / 2; return <path key={relation.id} d={`M${from.x + NODE_WIDTH},${from.y + NODE_HEIGHT / 2} H${middle} V${to.y + NODE_HEIGHT / 2} H${to.x}`} data-tone={relation.tone}><title>{relation.label}</title></path>; })}</svg>
			{visible.map((item) => { const location = point(item); return <article key={item.id} className="ts-agent-flow__node" data-kind={item.kind} data-live={item.status === 'running'} style={{ '--node-x': `${location.x}px`, '--node-y': `${location.y}px` } as CSSProperties} onPointerDown={(event) => startDrag(event, item)} onPointerMove={moveDrag} onPointerUp={(event) => void endDrag(event, item)}><span>{item.kind === 'signal' ? 'Signal contract' : item.tags?.[0] ?? item.kind}</span><CommandOverlayTrigger target={item}><strong>{item.title}</strong><small>{item.status ?? 'Inspect'} →</small></CommandOverlayTrigger></article>; })}
		</div><div className="ts-agent-flow__minimap" aria-hidden="true">{visible.map((item) => { const location = point(item); return <i key={item.id} data-kind={item.kind} style={{ left: `${location.x / bounds.width * 100}%`, top: `${location.y / bounds.height * 100}%` }} />; })}</div></div>
		<details className="ts-agent-flow__index"><summary>Accessible signal relation list ({links.length})</summary><ul>{links.map((relation) => { const from = visible.find((item) => item.id === relation.from); const to = visible.find((item) => item.id === relation.to); return from && to ? <li key={relation.id}><CommandOverlayTrigger target={from}>{from.title}</CommandOverlayTrigger><span>{relation.label}</span><CommandOverlayTrigger target={to}>{to.title}</CommandOverlayTrigger></li> : null; })}</ul></details>
		{creating==='agent'&&authoringEndpoint?<AgentCreator projects={projects} saveEndpoint={authoringEndpoint} onClose={()=>setCreator(null)} />:null}
		{creating==='group'&&authoringEndpoint?<GroupCreator projects={projects} saveEndpoint={authoringEndpoint.replace(/\/authoring$/u,'/authoring-group')} onClose={()=>setCreator(null)} />:null}
	</section>;
}
