import { useState } from 'react';

const templates = {
	'research-steward': { label:'Research steward', agentClass:'research', description:'Investigates objectives, publishes evidence and escalates uncertainty.', handler:'writer', mutations:['linked_note:create','question:create'], signal:'evidence-ready' },
	'proposal-reviewer': { label:'Proposal reviewer', agentClass:'review', description:'Reviews proposals against evidence, policy and project objectives.', handler:'writer', mutations:['proposal_feedback:create','question:create'], signal:'review-ready' },
	'implementation-guide': { label:'Implementation guide', agentClass:'engineering', description:'Plans decision-aligned implementation and reports verifiable changes.', handler:'actor', mutations:['linked_note:create','proposal_feedback:create'], signal:'implementation-ready' },
} as const;
type TemplateId = keyof typeof templates;

function profile(name:string,template:typeof templates[TemplateId],focus:string){return {activityType:'planning',enabled:true,handler:template.handler,prompt:{system:`You are ${name}. ${template.description} Use TreeDX-backed content operations, distinguish evidence from inference, and stay within assigned authority.`,task:focus||template.description},planningIntent:{stage:'discovery',objective:focus||template.description,artifactKind:'linked_note',subjectModel:'objective',subjectId:null},branchPolicy:{kind:'staging-content',base:'staging'},contentAccess:{read:{models:['objective','note','proposal','decision','knowledge','agent'],actions:['describe','query','read']},write:{models:['note','question'],actions:['create','link','validate','commit']},commit:{allowed:true}},tools:{allowed:['treeseed.content.describe','treeseed.content.query','treeseed.content.read','treedx.build_context','treedx.read_repository_files','treeseed.content.create','treeseed.content.link','treeseed.content.validate','treeseed.content.commit'],denied:[]},signals:{subscribesTo:[{contract:'workday-started'}],publishes:[template.signal]},outputs:{messageTypes:[template.signal.replace(/-/gu,'_')],modelMutations:template.mutations},questionPolicy:{blockExecutionWhenCreated:true,defaultAnswerPolicy:{kind:'team-human'}},execution:{providerPreference:['codex'],maxRuntimeSeconds:600,maxRetries:1,verificationRequired:false}};}

export function AgentCreator({ projects,saveEndpoint,onClose }: { projects:Array<[string,string]>; saveEndpoint:string; onClose:()=>void }) {
	const [projectId,setProjectId]=useState(projects[0]?.[0] ?? ''); const [name,setName]=useState(''); const [templateId,setTemplateId]=useState<TemplateId>('research-steward'); const [focus,setFocus]=useState(''); const [state,setState]=useState(''); const template=templates[templateId];
	async function create(){if(!projectId||!name.trim()){setState('Choose a project and give the agent a display name.');return;}const intent={name:name.trim(),description:template.description,purpose:focus.trim()||template.description,responsibilities:['Inspect authoritative project context','Produce durable evidence with provenance','Escalate uncertainty as a linked question'],durableInstructions:'Use TreeDX for every project-content read and mutation. Never approve decisions or widen assigned authority.',agentClass:template.agentClass,template:`agent-lab/${templateId}`,enabled:true,designMaturity:'draft',activityProfiles:{planning:profile(name.trim(),template,focus.trim())}};setState('Generating identity, validating contracts and committing through TreeDX…');const response=await fetch(saveEndpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId,intent,changeSummary:`Create ${template.label} agent ${name.trim()}`})});const result=await response.json();if(!response.ok){setState(result.error ?? 'Agent creation failed.');return;}setState(`Created ${String(result.payload?.changedPaths?.[0] ?? '')} at ${String(result.payload?.commit ?? '').slice(0,12)}.`);setTimeout(onClose,650);}
	return <section className="ts-agent-creator" role="dialog" aria-modal="true" aria-label="Create repository agent"><header><div><span>Template-first agent genesis</span><h3>Grow an agent</h3><p>You describe the role. Agent Lab generates and locks identity, class linkage, defaults and repository placement.</p></div><button type="button" onClick={onClose} aria-label="Close creator">×</button></header><div><label><span>Project environment</span><select value={projectId} onChange={(event)=>setProjectId(event.target.value)}>{projects.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label><span>Anatomy template</span><select value={templateId} onChange={(event)=>setTemplateId(event.target.value as TemplateId)}>{Object.entries(templates).map(([id,value])=><option key={id} value={id}>{value.label}</option>)}</select></label><label><span>Display name</span><input value={name} onChange={(event)=>setName(event.target.value)} placeholder="Evidence Cartographer"/></label><label><span>Primary focus</span><input value={focus} onChange={(event)=>setFocus(event.target.value)} placeholder="Map unresolved launch risks"/></label></div><footer><button type="button" onClick={onClose}>Cancel</button><button type="button" onClick={()=>void create()}>Generate & reconcile</button>{state?<span role="status">{state}</span>:null}</footer></section>;
}
