import { useState } from 'react';
import { requestJson } from '../../../forms-client.ts';
import { YamlIde,type YamlIdeDiagnostic } from './YamlIde.tsx';
import { WorkspaceFocusSurface } from '../../workspace-surfaces/WorkspaceFocusSurface.tsx';
import { EvidenceDiffViewer } from '../../workspace-surfaces/EvidenceDiffViewer.tsx';
import { useWorkspaceSurfaceMode } from '../../workspace-surfaces/use-workspace-surface-mode.ts';

export function StructuredSourceEditor({ title, description, source, language = 'yaml', saveEndpoint, expectedBase, projectId = '', projectName = 'Selected project', path = '', onSaved }: { title: string; description: string; source: string; language?: 'yaml' | 'mdx'; saveEndpoint: string; expectedBase?: string | null; projectId?: string; projectName?: string; path?: string; onSaved?: (commit: string) => void }) {
	const [value, setValue] = useState(source); const [selectedPath, setSelectedPath] = useState(path); const [state, setState] = useState<'idle' | 'saving' | 'saved' | 'conflict' | 'error'>('idle'); const [message, setMessage] = useState(''); const [diagnostics,setDiagnostics] = useState<YamlIdeDiagnostic[]>([]); const [mode,setMode] = useState<'source' | 'changes'>('source');
	const [surfaceMode,changeSurfaceMode]=useWorkspaceSurfaceMode({surfaceId:'editor'});
	async function save() { setState('saving'); setMessage(''); setDiagnostics([]); try { const response = await requestJson(saveEndpoint, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ source: value, language, expectedBase, projectId, path: selectedPath }) }); const result = await response.json(); if (response.status === 409) { setState('conflict'); setMessage(result.error ?? 'The authoring branch changed. Compare and reload before saving.'); return; } if (!response.ok) { setDiagnostics(Array.isArray(result.diagnostics) ? result.diagnostics.map((item: Record<string,unknown>) => ({ message: String(item.message ?? 'Invalid definition.'), line: Number(item.line) || undefined, column: Number(item.column) || undefined })) : []); throw new Error(result.error ?? `Save failed (${response.status}).`); } setState('saved'); setMessage(`Committed ${String(result.commit ?? result.payload?.commit ?? '').slice(0, 12)}`); onSaved?.(result.commit ?? result.payload?.commit); } catch (error) { setState('error'); setMessage(error instanceof Error ? error.message : 'Save failed.'); } }
	const changed = value !== source;
	return <WorkspaceFocusSurface id={`source-editor:${projectId}:${selectedPath}`} label={`${language.toUpperCase()} editor`} mode={surfaceMode} boundary="workspace-content" onModeChange={changeSurfaceMode} headerContext={<span><strong>{title}</strong> · {projectName} · {expectedBase?.slice(0,12) ?? 'new file'}</span>}><section className="ts-command-source"><header><div><span>{language.toUpperCase()} IDE</span><h3>{title}</h3><p>{description}</p></div><div className="ts-command-source__actions"><button type="button" aria-pressed={mode === 'source'} onClick={() => setMode('source')}>Source</button><button type="button" aria-pressed={mode === 'changes'} onClick={() => setMode('changes')}>Changes</button><button type="button" onClick={save} disabled={state === 'saving' || !projectId || !selectedPath || !changed}>{state === 'saving' ? 'Validating…' : 'Validate & commit'}</button></div></header><div className="ts-command-source__target"><div><span>Project</span><strong>{projectName}</strong></div><label><span>Repository path</span><input value={selectedPath} onChange={(event) => setSelectedPath(event.target.value)} /></label></div>{mode === 'source' ? language === 'yaml' ? <YamlIde value={value} onChange={(next) => { setValue(next); setState('idle'); }} label={`${title} YAML source`} diagnostics={diagnostics} /> : <textarea spellCheck={false} value={value} onChange={(event) => { setValue(event.target.value); setState('idle'); }} aria-label={`${title} source`} /> : <EvidenceDiffViewer base={source} current={value} />}{message ? <p className="ts-command-source__message" data-state={state}>{message}</p> : null}</section></WorkspaceFocusSurface>;
}
