import { useState } from 'react';

type Row = Record<string, unknown>;
type ProfileTab = 'input' | 'relation' | 'projection' | 'output' | 'runtime';
function object(value: unknown): Row { return value && typeof value === 'object' && !Array.isArray(value) ? value as Row : {}; }
function list(value: unknown) { return Array.isArray(value) ? value.map(String) : []; }
function csv(value: unknown) { return list(value).join(', '); }
function values(value: string) { return value.split(',').map((entry) => entry.trim()).filter(Boolean); }
function number(value: string) { return value ? Number(value) : undefined; }

function InputPanel({ profile, onChange }: { profile: Row; onChange(value: Row): void }) {
	const prompt = object(profile.prompt); const signals = object(profile.signals); const subscriptions = Array.isArray(signals.subscribesTo) ? signals.subscribesTo.map(object) : [];
	const contracts = subscriptions.map((entry) => String(entry.contract ?? '')).filter(Boolean);
	const updateContracts = (next: string[]) => onChange({ ...profile, signals: { ...signals, subscribesTo: next.map((contract) => subscriptions.find((entry) => entry.contract === contract) ?? { contract }) } });
	return <div className="ts-agent-designer__panel-grid"><section className="ts-agent-designer__card"><div className="ts-agent-designer__card-head"><div><h4>Signal subscriptions</h4><p>Registered input contract IDs; existing policies and filters are preserved.</p></div><code>signals.subscribesTo[]</code></div><label><span>Contracts · comma separated</span><input value={contracts.join(', ')} onChange={(event) => updateContracts(values(event.target.value))} /></label></section><section className="ts-agent-designer__card"><div className="ts-agent-designer__card-head"><h4>Instructions</h4><code>prompt</code></div><label><span>System instruction</span><textarea rows={8} value={String(prompt.system ?? '')} onChange={(event) => onChange({ ...profile, prompt: { ...prompt, system: event.target.value } })} /></label><label><span>Task instruction</span><textarea rows={5} value={String(prompt.task ?? '')} onChange={(event) => onChange({ ...profile, prompt: { ...prompt, task: event.target.value } })} /></label></section></div>;
}

function RelationPanel({ profile, onChange }: { profile: Row; onChange(value: Row): void }) {
	const access = object(profile.contentAccess); const read = object(access.read); const write = object(access.write); const commit = object(access.commit);
	const scope = (name: 'read' | 'write', current: Row, field: string, value: string[]) => onChange({ ...profile, contentAccess: { ...access, [name]: { ...current, [field]: value } } });
	return <div className="ts-agent-designer__panel-grid"><section className="ts-agent-designer__card"><div className="ts-agent-designer__card-head"><div><h4>Read context</h4><p>Authorized TreeDX models and relation boundaries.</p></div><code>contentAccess.read</code></div><label><span>Models</span><input value={csv(read.models)} onChange={(event) => scope('read', read, 'models', values(event.target.value))} /></label><label><span>Relations</span><input value={csv(read.relations)} onChange={(event) => scope('read', read, 'relations', values(event.target.value))} /></label><label><span>Paths</span><input value={csv(read.paths)} onChange={(event) => scope('read', read, 'paths', values(event.target.value))} /></label></section><section className="ts-agent-designer__card"><div className="ts-agent-designer__card-head"><div><h4>Write context</h4><p>Explicit content mutations; assignment authority still applies.</p></div><code>contentAccess.write</code></div><label><span>Models</span><input value={csv(write.models)} onChange={(event) => scope('write', write, 'models', values(event.target.value))} /></label><label><span>Actions</span><input value={csv(write.actions)} onChange={(event) => scope('write', write, 'actions', values(event.target.value))} /></label><label className="ts-agent-designer__check"><input type="checkbox" checked={commit.allowed === true} onChange={(event) => onChange({ ...profile, contentAccess: { ...access, commit: { allowed: event.target.checked } } })} /> Commit allowed</label></section></div>;
}

function ProjectionPanel({ profile, onChange }: { profile: Row; onChange(value: Row): void }) {
	const tools = object(profile.tools); const branch = object(profile.branchPolicy);
	return <div className="ts-agent-designer__panel-grid"><section className="ts-agent-designer__card"><div className="ts-agent-designer__card-head"><div><h4>Tools and plan</h4><p>The mediated tools this profile may or may not invoke.</p></div><code>tools</code></div><label><span>Allowed tools</span><textarea rows={5} value={list(tools.allowed).join('\n')} onChange={(event) => onChange({ ...profile, tools: { ...tools, allowed: values(event.target.value.replaceAll('\n', ',')) } })} /></label><label><span>Denied tools</span><textarea rows={4} value={list(tools.denied).join('\n')} onChange={(event) => onChange({ ...profile, tools: { ...tools, denied: values(event.target.value.replaceAll('\n', ',')) } })} /></label></section><section className="ts-agent-designer__card"><div className="ts-agent-designer__card-head"><div><h4>Repository boundary</h4><p>Branch behavior is validated as part of the profile.</p></div><code>branchPolicy</code></div><label><span>Policy kind</span><select value={String(branch.kind ?? 'read-only')} onChange={(event) => onChange({ ...profile, branchPolicy: { ...branch, kind: event.target.value } })}>{['read-only','main-planning-content','staging-content','assignment-feature','staging-release'].map((value) => <option key={value}>{value}</option>)}</select></label><label><span>Base branch</span><select value={String(branch.base ?? 'main')} onChange={(event) => onChange({ ...profile, branchPolicy: { ...branch, base: event.target.value } })}><option>main</option><option>staging</option></select></label></section></div>;
}

function OutputPanel({ profile, onChange }: { profile: Row; onChange(value: Row): void }) {
	const outputs = object(profile.outputs); const signals = object(profile.signals); const planning = object(profile.planningIntent);
	return <div className="ts-agent-designer__panel-grid"><section className="ts-agent-designer__card"><div className="ts-agent-designer__card-head"><div><h4>Result structures</h4><p>Validated message and content-model outputs.</p></div><code>outputs</code></div><label><span>Message types</span><input value={csv(outputs.messageTypes)} onChange={(event) => onChange({ ...profile, outputs: { ...outputs, messageTypes: values(event.target.value) } })} /></label><label><span>Model mutations</span><input value={csv(outputs.modelMutations)} onChange={(event) => onChange({ ...profile, outputs: { ...outputs, modelMutations: values(event.target.value) } })} /></label><label><span>Published signal IDs</span><input value={csv(signals.publishes)} onChange={(event) => onChange({ ...profile, signals: { ...signals, publishes: values(event.target.value) } })} /></label></section><section className="ts-agent-designer__card"><div className="ts-agent-designer__card-head"><div><h4>Planning intent</h4><p>Optional work semantics for planning profiles.</p></div><code>planningIntent</code></div><label><span>Objective</span><input value={String(planning.objective ?? '')} onChange={(event) => onChange({ ...profile, planningIntent: { ...planning, objective: event.target.value || undefined } })} /></label><label><span>Proposal types</span><input value={csv(planning.proposalTypes)} onChange={(event) => onChange({ ...profile, planningIntent: { ...planning, proposalTypes: values(event.target.value) } })} /></label><label><span>Artifact kind</span><input value={String(planning.artifactKind ?? '')} onChange={(event) => onChange({ ...profile, planningIntent: { ...planning, artifactKind: event.target.value || undefined } })} /></label></section></div>;
}

function RuntimePanel({ profile, onChange }: { profile: Row; onChange(value: Row): void }) {
	const execution = object(profile.execution); const set = (name: string, value: unknown) => onChange({ ...profile, execution: { ...execution, [name]: value } });
	return <section className="ts-agent-designer__card"><div className="ts-agent-designer__card-head"><div><h4>Runtime bounds</h4><p>Provider matching and closeout limits carried into assignment execution.</p></div><code>execution</code></div><div className="ts-agent-designer__fields"><label className="wide"><span>Required capabilities</span><input value={csv(execution.requiredCapabilities)} onChange={(event) => set('requiredCapabilities', values(event.target.value))} /></label><label><span>Maximum runtime · seconds</span><input type="number" min="1" value={String(execution.maxRuntimeSeconds ?? '')} onChange={(event) => set('maxRuntimeSeconds', number(event.target.value))} /></label><label><span>Closeout warning · seconds</span><input type="number" min="1" value={String(execution.closeoutWarningSeconds ?? '')} onChange={(event) => set('closeoutWarningSeconds', number(event.target.value))} /></label><label><span>Maximum retries</span><input type="number" min="0" value={String(execution.maxRetries ?? '')} onChange={(event) => set('maxRetries', number(event.target.value))} /></label><label><span>Maximum total tokens</span><input type="number" min="1" value={String(execution.maxTotalTokens ?? '')} onChange={(event) => set('maxTotalTokens', number(event.target.value))} /></label><label><span>Warning tokens</span><input type="number" min="1" value={String(execution.warningTokens ?? '')} onChange={(event) => set('warningTokens', number(event.target.value))} /></label><label className="ts-agent-designer__check"><input type="checkbox" checked={execution.verificationRequired === true} onChange={(event) => set('verificationRequired', event.target.checked)} /> Verification required</label></div></section>;
}

export function AgentProfilePanel({ profileId, profile, onChange }: { profileId: string; profile: Row; onChange(value: Row): void }) {
	const [tab, setTab] = useState<ProfileTab>('input');
	const tabs: Array<[ProfileTab, string]> = [['input','Input'],['relation','Relation'],['projection','Projection'],['output','Output'],['runtime','Runtime']];
	return <div className="ts-agent-designer__page"><header><span>Activity profile / {String(profile.handler ?? 'unassigned')}</span><div><h2>{profileId}</h2><label className="ts-agent-designer__toggle"><input type="checkbox" checked={profile.enabled !== false} onChange={(event) => onChange({ ...profile, enabled: event.target.checked })} /> Enabled</label></div><p>Configure the exact runtime profile; assignment scope and provider selection remain control-plane authority.</p></header><nav className="ts-agent-designer__tabs" aria-label={`${profileId} configuration`}>{tabs.map(([id,label]) => <button key={id} type="button" role="tab" aria-selected={tab === id} onClick={() => setTab(id)}>{label}</button>)}</nav>{tab === 'input' ? <InputPanel profile={profile} onChange={onChange} /> : tab === 'relation' ? <RelationPanel profile={profile} onChange={onChange} /> : tab === 'projection' ? <ProjectionPanel profile={profile} onChange={onChange} /> : tab === 'output' ? <OutputPanel profile={profile} onChange={onChange} /> : <RuntimePanel profile={profile} onChange={onChange} />}</div>;
}
