import RichMarkdownEditor from '../editors/RichMarkdownEditor.tsx';

type Row = Record<string, unknown>;
function object(value: unknown): Row { return value && typeof value === 'object' && !Array.isArray(value) ? value as Row : {}; }
function list(value: unknown) { return Array.isArray(value) ? value.map(String) : []; }
function lines(value: string) { return value.split('\n').map((entry) => entry.trim()).filter(Boolean); }

export function AgentIdentityPanel({ definition, contentBody, context, onDefinitionChange, onContentBodyChange }: {
	definition: Row;
	contentBody: string;
	context: boolean;
	onDefinitionChange(value: Row): void;
	onContentBodyChange(value: string): void;
}) {
	const identity = object(definition.identity);
	const field = (name: string, value: unknown) => onDefinitionChange({ ...definition, [name]: value });
	const identityField = (name: string, value: unknown) => field('identity', { ...identity, [name]: value });
	if (context) return <div className="ts-agent-designer__page"><header><span>Agent / inherited</span><h2>Common context</h2><p>Configure the shared instructions and team groups supported by the current agent-definition contract.</p></header><section className="ts-agent-designer__card"><label className="wide"><span>Durable instructions</span><textarea rows={10} value={String(identity.durableInstructions ?? '')} onChange={(event) => identityField('durableInstructions', event.target.value)} /></label></section><section className="ts-agent-designer__card"><div className="ts-agent-designer__fields"><label><span>Primary group</span><input value={String(definition.primaryGroupId ?? '')} onChange={(event) => field('primaryGroupId', event.target.value)} /></label><label><span>Group IDs · one per line</span><textarea rows={5} value={list(definition.groupIds).join('\n')} onChange={(event) => field('groupIds', lines(event.target.value))} /></label></div></section></div>;
	return <div className="ts-agent-designer__page"><header><span>Agent</span><h2>Identity & purpose</h2><p>Define how the agent is addressed, allocated, and understood.</p></header><section className="ts-agent-designer__card"><div className="ts-agent-designer__card-head"><div><h4>Identity</h4><p>Validated frontmatter fields</p></div><code>frontmatter</code></div><div className="ts-agent-designer__fields"><label><span>Human-readable name</span><input value={String(definition.name ?? definition.title ?? '')} onChange={(event) => field('name', event.target.value)} /></label><label><span>Agent class</span><input value={String(definition.agentClass ?? '')} onChange={(event) => field('agentClass', event.target.value)} /></label><label><span>Enabled</span><select value={definition.enabled === false ? 'false' : 'true'} onChange={(event) => field('enabled', event.target.value === 'true')}><option value="true">Enabled</option><option value="false">Dormant</option></select></label><label><span>Design maturity</span><select value={String(definition.designMaturity ?? 'draft')} onChange={(event) => field('designMaturity', event.target.value)}>{['draft','validated','simulated','proven'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="wide"><span>Description</span><textarea rows={3} value={String(definition.description ?? '')} onChange={(event) => field('description', event.target.value)} /></label><label className="wide"><span>Internal purpose guide</span><textarea rows={4} value={String(identity.purpose ?? '')} onChange={(event) => identityField('purpose', event.target.value)} /></label><label className="wide"><span>Responsibilities · one per line</span><textarea rows={5} value={list(identity.responsibilities).join('\n')} onChange={(event) => identityField('responsibilities', lines(event.target.value))} /></label></div></section><section className="ts-agent-designer__card"><div className="ts-agent-designer__card-head"><div><h4>Agent content file</h4><p>The MDX body shown when people inspect this agent.</p></div><code>MDX body</code></div><RichMarkdownEditor name="agent-profile-body" label="External profile" initialMarkdown={contentBody} onChange={onContentBodyChange} /></section></div>;
}
