import { useMemo,useState } from 'react';
import { parse,stringify } from 'yaml';
import type { CommandEntityDetail } from '../types.ts';

type Row = Record<string,unknown>;
function object(value: unknown): Row { return value && typeof value === 'object' && !Array.isArray(value) ? value as Row : {}; }
function list(value: unknown) { return Array.isArray(value) ? value : []; }
function sourceParts(source: string) { const match = source.match(/^---\s*\n([\s\S]*?)\n---\s*\n?/u); return match ? { frontmatter:object(parse(match[1] ?? '')),body:source.slice(match[0].length) } : { frontmatter:{},body:source }; }
function contracts(value: unknown) { return list(value).map((entry) => typeof entry === 'string' ? entry : String(object(entry).contract ?? '')).filter(Boolean); }
function csv(value: unknown) { return list(value).map(String).filter(Boolean).join(', '); }

export function AgentDefinitionEditor({ detail,authoring,saveEndpoint }: { detail: CommandEntityDetail; authoring: Row; saveEndpoint: string }) {
	const original = useMemo(() => sourceParts(String(authoring.source ?? '')),[authoring.source]);
	const [definition,setDefinition] = useState<Row>(original.frontmatter); const [cloneIdentity,setCloneIdentity] = useState(''); const [state,setState] = useState<'idle'|'saving'|'saved'|'error'|'conflict'>('idle'); const [message,setMessage] = useState('');
	const profiles = object(definition.activityProfiles);
	function field(name: string,value: unknown) { setDefinition((current) => ({ ...current,[name]:value })); setState('idle'); }
	function profileField(profileId: string,name: string,value: unknown) { setDefinition((current) => ({ ...current,activityProfiles:{ ...object(current.activityProfiles),[profileId]:{ ...object(object(current.activityProfiles)[profileId]),[name]:value } } })); setState('idle'); }
	function signalField(profileId: string,direction: 'subscribesTo'|'publishes',value: string) { const profile = object(profiles[profileId]); const signals = object(profile.signals); const values = value.split(',').map((entry) => entry.trim()).filter(Boolean); const next = direction === 'publishes' ? values : values.map((contract) => list(signals.subscribesTo).map(object).find((entry) => entry.contract === contract) ?? { contract }); profileField(profileId,'signals',{ ...signals,[direction]:next }); }
	function executionField(profileId: string,name: string,value: unknown) { const profile = object(profiles[profileId]); profileField(profileId,'execution',{ ...object(profile.execution),[name]:value }); }
	async function commit(next: Row,path=String(authoring.path ?? ''),summary='Update agent definition') { setState('saving'); setMessage('Validating signal references and committing through TreeDX…'); const source = `---\n${stringify(next).trim()}\n---\n${original.body}`; const response = await fetch(saveEndpoint,{ method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({ projectId:authoring.projectId,path,expectedBase:authoring.expectedBase,source,changeSummary:summary }) }); const result=await response.json(); if(response.ok){setState('saved');setMessage(`Committed ${String(result.payload?.commit ?? '').slice(0,12)} and reconciled the live roster.`);}else{setState(response.status===409?'conflict':'error');setMessage(result.error ?? 'The agent definition could not be committed.');} }
	async function clone() { const identity=cloneIdentity.trim().toLowerCase().replace(/[^a-z0-9]+/gu,'-').replace(/^-|-$/gu,''); if(!identity){setState('error');setMessage('Provide a new clone identity.');return;} const next={...definition,id:`agent:${identity}`,slug:identity,title:`${String(definition.title ?? definition.name ?? 'Agent')} copy`,name:`${String(definition.name ?? definition.title ?? 'Agent')} copy`,enabled:true}; await commit(next,`src/content/agents/${identity}.mdx`,`Clone agent as ${identity}`); }
	async function deactivate() { if(!confirm(`Deactivate ${detail.title}? Future workdays will exclude it after this commit.`)) return; const next={...definition,enabled:false}; setDefinition(next); await commit(next,String(authoring.path ?? ''),`Deactivate agent ${String(definition.slug ?? detail.title)}`); }
	return <section className="ts-agent-editor">
		<header><span>Repository agent</span><h3>{detail.title}</h3><p>Shape identity and execution behavior here; use Inspector for the complete canonical record.</p></header>
		<div className="ts-agent-editor__identity"><label><span>Name</span><input value={String(definition.name ?? definition.title ?? '')} onChange={(event)=>field('name',event.target.value)} /></label><label><span>Agent class</span><input value={String(definition.agentClass ?? '')} onChange={(event)=>field('agentClass',event.target.value)} /></label><label><span>Description</span><textarea rows={3} value={String(definition.description ?? '')} onChange={(event)=>field('description',event.target.value)} /></label></div>
		<div className="ts-agent-editor__profiles">{Object.entries(profiles).map(([profileId,raw])=>{const profile=object(raw);const execution=object(profile.execution);const prompt=object(profile.prompt);const signals=object(profile.signals);return <details key={profileId} open><summary><span>{profileId}</span><strong>{String(profile.handler ?? 'Handler not selected')}</strong></summary><div>
			<label><span>Handler</span><input value={String(profile.handler ?? '')} onChange={(event)=>profileField(profileId,'handler',event.target.value)} /></label><label><span>Execution provider</span><input value={String(execution.provider ?? execution.executionProvider ?? '')} onChange={(event)=>executionField(profileId,'provider',event.target.value)} /></label><label><span>Model / processor</span><input value={String(execution.model ?? '')} onChange={(event)=>executionField(profileId,'model',event.target.value)} /></label><label><span>Timebox seconds</span><input type="number" min="1" value={String(execution.timeboxSeconds ?? execution.maxRuntimeSeconds ?? '')} onChange={(event)=>executionField(profileId,'timeboxSeconds',Number(event.target.value))} /></label>
			<label className="wide"><span>Input signals</span><input value={contracts(signals.subscribesTo).join(', ')} onChange={(event)=>signalField(profileId,'subscribesTo',event.target.value)} /></label><label className="wide"><span>Output signals</span><input value={csv(signals.publishes)} onChange={(event)=>signalField(profileId,'publishes',event.target.value)} /></label><label className="wide"><span>System prompt</span><textarea rows={4} value={String(prompt.system ?? '')} onChange={(event)=>profileField(profileId,'prompt',{...prompt,system:event.target.value})} /></label><label className="wide"><span>Task prompt</span><textarea rows={4} value={String(prompt.task ?? '')} onChange={(event)=>profileField(profileId,'prompt',{...prompt,task:event.target.value})} /></label><label className="wide"><span>Content permissions</span><textarea rows={3} value={stringify(object(profile.contentAccess)).trim()} onChange={(event)=>{try{profileField(profileId,'contentAccess',object(parse(event.target.value)));}catch{}}} /></label><label className="wide"><span>Tool permissions</span><input value={csv(profile.tools ?? profile.allowedTools)} onChange={(event)=>profileField(profileId,'tools',event.target.value.split(',').map((entry)=>entry.trim()).filter(Boolean))} /></label>
		</div></details>;})}</div>
		<footer><div className="ts-agent-editor__lifecycle"><button type="button" disabled={state==='saving'} onClick={()=>void commit(definition)}>{state==='saving'?'Validating…':'Validate & commit agent'}</button><label><span>Clone identity</span><input value={cloneIdentity} onChange={(event)=>setCloneIdentity(event.target.value)} placeholder="new-agent" /></label><button type="button" disabled={state==='saving'} onClick={()=>void clone()}>Clone</button>{definition.enabled!==false?<button type="button" data-tone="danger" disabled={state==='saving'} onClick={()=>void deactivate()}>Deactivate</button>:null}</div>{message?<span role="status" data-state={state}>{message}</span>:null}</footer>
	</section>;
}
