import { useCallback, useEffect, useMemo, useState } from 'react';
import DynamicPieAllocationInput, { type PieAllocationSlice, type PieAllocationValidity } from '../pie-allocation/DynamicPieAllocationInput.tsx';
import type { AllocationSnapshot } from './types.ts';
import { useRealtimeResource } from './use-realtime-resource.ts';

type Scope = 'portfolio' | 'agent-class';
function grouped(snapshot: AllocationSnapshot) { return Object.fromEntries(snapshot.projects.map((project) => [project.id, snapshot.agentClasses.filter((item) => item.projectId === project.id)])); }
function sameAllocation(left: PieAllocationSlice[], right: PieAllocationSlice[]) { return left.length === right.length && left.every((item) => Math.abs(item.percentage - (right.find((entry) => entry.id === item.id)?.percentage ?? -1)) < .001); }

export function AllocationManagementPanel({ initialSnapshot, endpoint, csrfToken, realtime }: { initialSnapshot: AllocationSnapshot; endpoint: string; csrfToken: string; realtime: { enabled: boolean; intervalMs: number } }) {
	const target = useCallback(() => endpoint, [endpoint]); const parse = useCallback((payload: unknown) => ({ data: payload as AllocationSnapshot }), []);
	const resource = useRealtimeResource({ initialData: initialSnapshot, endpoint: target, intervalMs: Math.max(10_000, realtime.intervalMs * 2), enabled: realtime.enabled, parse });
	const [projectId, setProjectId] = useState(initialSnapshot.projects[0]?.id ?? ''); const [projects, setProjects] = useState<PieAllocationSlice[]>(initialSnapshot.projects);
	const [activeScope, setActiveScope] = useState<Scope>('portfolio');
	const [classDrafts, setClassDrafts] = useState<Record<string, PieAllocationSlice[]>>(() => grouped(initialSnapshot)); const [projectDirty, setProjectDirty] = useState(false); const [classDirty, setClassDirty] = useState<Record<string, boolean>>({});
	const [valid, setValid] = useState<Record<string, boolean>>({}); const [messages, setMessages] = useState<Partial<Record<Scope, string>>>({}); const classes = classDrafts[projectId] ?? [];
	useEffect(() => { if (!projectDirty) setProjects(resource.data.projects); setProjectId((current) => resource.data.projects.some((item) => item.id === current) ? current : resource.data.projects[0]?.id ?? ''); setClassDrafts((current) => { const next = { ...current }; for (const project of resource.data.projects) if (!classDirty[project.id]) next[project.id] = resource.data.agentClasses.filter((item) => item.projectId === project.id); return next; }); }, [classDirty, projectDirty, resource.data.agentClasses, resource.data.projects]);
	const projectChanged = (next: PieAllocationSlice[], state: PieAllocationValidity) => { setProjects(next); setProjectDirty(!sameAllocation(next, resource.data.projects)); setValid((value) => ({ ...value, portfolio: state.valid })); };
	const classesChanged = (next: PieAllocationSlice[], state: PieAllocationValidity) => { setClassDrafts((value) => ({ ...value, [projectId]: next })); setClassDirty((value) => ({ ...value, [projectId]: !sameAllocation(next, resource.data.agentClasses.filter((item) => item.projectId === projectId)) })); setValid((value) => ({ ...value, [`class:${projectId}`]: state.valid })); };
	const requestId = () => globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random()}`;
	const save = async (scope: Scope) => {
		setMessages((value) => ({ ...value, [scope]: 'Applying allocation…' })); const slices = scope === 'portfolio' ? projects : classes;
		const response = await fetch(endpoint, { method: 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json', 'x-treeseed-csrf': csrfToken }, body: JSON.stringify({ scope, projectId: scope === 'agent-class' ? projectId : undefined, slices, expectedActiveAllocationSetId: resource.data.activeAllocationSetId, requestId: requestId() }) });
		const body = await response.json().catch(() => ({})); if (!response.ok) { setMessages((value) => ({ ...value, [scope]: body.error ?? 'Allocation could not be applied.' })); return; }
		resource.replaceData((body.payload ?? body) as AllocationSnapshot); if (scope === 'portfolio') setProjectDirty(false); else setClassDirty((value) => ({ ...value, [projectId]: false })); setMessages((value) => ({ ...value, [scope]: scope === 'portfolio' ? 'Portfolio allocation is active.' : 'Agent-class allocation is active.' })); resource.reconnect();
	};
	const stats = useMemo(() => [{ label: 'Budget', value: resource.data.credits.budget }, { label: 'Requested', value: resource.data.credits.requested }, { label: 'Reserved', value: resource.data.credits.reserved }, { label: 'Committed / spent', value: `${resource.data.credits.committed} / ${resource.data.credits.spent}` }, { label: 'Remaining', value: resource.data.credits.remaining }, { label: 'Overrun', value: resource.data.credits.overrun }], [resource.data.credits]);
	return <section className="ts-allocation-monitor" aria-label="Capacity allocation">
		<header className="ts-monitor-chart-header"><div><small>Portfolio capacity</small><strong>Credits and direction</strong><span>Canonical workday demand, reservation, usage, and settlement accounting.</span></div><span data-status={resource.status}>{resource.status}</span></header>
		<div className="ts-allocation-monitor__stats">{stats.map((stat) => <span key={stat.label}><small>{stat.label}</small><strong>{stat.value ?? '—'}</strong></span>)}</div>
		<nav className="ts-allocation-monitor__scope" aria-label="Allocation scope"><button type="button" aria-pressed={activeScope === 'portfolio'} onClick={() => setActiveScope('portfolio')}><small>Portfolio</small><strong>Project targets</strong></button><button type="button" aria-pressed={activeScope === 'agent-class'} onClick={() => setActiveScope('agent-class')}><small>Project detail</small><strong>Agent-class targets</strong></button></nav>
		<div className="ts-allocation-monitor__editor">{activeScope === 'portfolio' ? <section aria-labelledby="portfolio-allocation-title"><header><div><h3 id="portfolio-allocation-title">Portfolio projects</h3><p>Distribute the portfolio target across every active team project.</p></div></header>{projects.length ? <DynamicPieAllocationInput density="compact" name="projectAllocation" initialValue={projects} disabled={!resource.data.canManage} onChange={projectChanged} ariaLabel="Portfolio project target allocation" /> : <p>No project allocation is available.</p>}<div className="ts-allocation-monitor__action"><span role="status">{messages.portfolio}</span>{resource.data.canManage ? <button type="button" disabled={!projectDirty || !valid.portfolio} onClick={() => void save('portfolio')}>Save portfolio</button> : null}</div></section> : <section aria-labelledby="class-allocation-title"><header><div><h3 id="class-allocation-title">Agent classes</h3><p>Set class targets for one project without changing the portfolio allocation.</p></div><label><span>Project</span><select value={projectId} onChange={(event) => setProjectId(event.target.value)}>{resource.data.projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label></header>{classes.length ? <DynamicPieAllocationInput density="compact" key={projectId} name="classAllocation" initialValue={classes} disabled={!resource.data.canManage} onChange={classesChanged} ariaLabel="Project agent-class target allocation" /> : <p>No active agent classes are configured for this project.</p>}<div className="ts-allocation-monitor__action"><span role="status">{messages['agent-class']}</span>{resource.data.canManage && classes.length ? <button type="button" disabled={!classDirty[projectId] || !valid[`class:${projectId}`]} onClick={() => void save('agent-class')}>Save agent classes</button> : null}</div></section>}</div>{!resource.data.canManage ? <footer><small>Team management permission is required to change allocation.</small></footer> : null}
	</section>;
}
